"""add token cost fields

Revision ID: 5e9f78b55a05
Revises: 9097fda2f0ed
Create Date: 2026-09-04 23:12:45.163533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9f78b55a05'
down_revision: Union[str, Sequence[str], None] = '9097fda2f0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    token_columns = (
        'input_tokens',
        'cached_input_tokens',
        'output_tokens',
        'reasoning_tokens',
    )

    for column_name in token_columns:
        op.add_column(
            'usage_events',
            sa.Column(
                column_name,
                sa.Integer(),
                nullable=False,
                server_default=sa.text('0'),
            ),
        )

    for column_name in token_columns:
        op.alter_column(
            'usage_events',
            column_name,
            server_default=None,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_events', 'reasoning_tokens')
    op.drop_column('usage_events', 'output_tokens')
    op.drop_column('usage_events', 'cached_input_tokens')
    op.drop_column('usage_events', 'input_tokens')
    # ### end Alembic commands ###
