"""add provider plan id

Revision ID: 9097fda2f0ed
Revises: 68e459671ad1
Create Date: 2026-08-28 23:50:43.685183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9097fda2f0ed'
down_revision: Union[str, Sequence[str], None] = '68e459671ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_provider_event_id'), 'payment_events', ['provider_event_id'], unique=True)
    op.drop_index(op.f('ix_stripe_events_stripe_event_id'), table_name='stripe_events')
    op.drop_table('stripe_events')
    op.add_column('plans', sa.Column('provider_plan_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'plans', ['provider_plan_id'])
    op.add_column('subscriptions', sa.Column('provider_customer_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('provider_subscription_id', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('subscriptions_stripe_customer_id_key'), 'subscriptions', type_='unique')
    op.drop_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', type_='unique')
    op.create_unique_constraint(None, 'subscriptions', ['provider_subscription_id'])
    op.create_unique_constraint(None, 'subscriptions', ['provider_customer_id'])
    op.drop_column('subscriptions', 'stripe_customer_id')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.create_unique_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', ['stripe_subscription_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('subscriptions_stripe_customer_id_key'), 'subscriptions', ['stripe_customer_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('subscriptions', 'provider_subscription_id')
    op.drop_column('subscriptions', 'provider_customer_id')
    op.drop_constraint(None, 'plans', type_='unique')
    op.drop_column('plans', 'provider_plan_id')
    op.create_table('stripe_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stripe_event_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('stripe_events_pkey'))
    )
    op.create_index(op.f('ix_stripe_events_stripe_event_id'), 'stripe_events', ['stripe_event_id'], unique=True)
    op.drop_index(op.f('ix_payment_events_provider_event_id'), table_name='payment_events')
    op.drop_table('payment_events')
    # ### end Alembic commands ###
